# Generated by Django 4.2.30 on 2026-05-24 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='click_count',
            field=models.BigIntegerField(default=0),
        ),
    ]
